if(NOT DEFINED PICO_SDK_PATH)
    if(EXISTS "${CMAKE_SOURCE_DIR}/pico-sdk")
        set(PICO_SDK_PATH "${CMAKE_SOURCE_DIR}/pico-sdk")
    else()
        message(FATAL_ERROR "could not find PICO SDK (maybe try cloning submodules)")
    endif()
endif()
